spring:
  application:
    name: FILE-PATH # ==> This is Service-Id
     
 
---
# Items that apply to ALL profiles:   
eureka:
  instance:
    appname: FILE-PATH  # ==> This is a instance of FILE-PATH-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8000  
  
---
spring:
  profiles: file-path-service-replica01
eureka:
  instance:
    appname: FILE-PATH-SERVICE  # ==> This is a instance of FILE-PATH-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
server:
  port: 8001   
     
---
spring:
  profiles: file-path-service-replica02
eureka:
  instance:
    appname: FILE-PATH-SERVICE  # ==> This is a instance of FILE-PATH-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
server:
  port: 8002
  
---
spring:
  profiles: file-path-service-replica03
eureka:
  instance:
    appname: file-path-SERVICE  # ==> This is a instance of FILE-PATH-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
server:
  port: 8003
  
---
spring:
  profiles: file-path-service-replica04
eureka:
  instance:
    appname: FILE-PATH-SERVICE  # ==> This is a instance of FILE-PATH-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
server:
  port: 8004  
  
---
spring:
  profiles: file-path-service-replica05
eureka:
  instance:
    appname: FILE-PATH-SERVICE  # ==> This is a instance of FILE-PATH-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
server:
  port: 8005